<?php
/** VaultOTP | Author: ItNexBD | https://itnexbd.com | https://github.com/NecharUddin */
require_once __DIR__.'/app/config.php';
init_db(); require_login(); if(!is_owner()){http_response_code(403);exit('Only the owner can manage sub-users.');}

$pdo=db();
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf(); $action=(string)($_POST['action']??'');
    if($action==='add_user'){
        try{
            $perms=[];
            foreach(['create_vault','manage_platforms','manage_backups','view_activity','reveal_codes','copy_codes','add_codes','mark_codes','delete_codes','edit_vaults','delete_vaults'] as $k)$perms[$k]=isset($_POST['perm'][$k]);
            $vaultIds=array_values(array_unique(array_map('intval',$_POST['vaults']??[])));
            $allVaults=!empty($_POST['all_vaults']); $ownerKey=key_from_session(); $id=create_user_account((string)($_POST['username']??''),(string)($_POST['display_name']??''),(string)($_POST['password']??''),(string)($_POST['role']??'member'),$allVaults,$ownerKey,$perms,$vaultIds); provision_user_access_keys($id,$allVaults,$vaultIds,$ownerKey);
            log_activity('Created sub-user'); flash('success','Sub-user created successfully.');
        }catch(Throwable $e){flash('error',$e->getMessage());}
        redirect('users.php');
    }
    if($action==='update_user'){
        $uid=(int)($_POST['user_id']??0); $u=$uid>0?get_user($uid):null;
        if(!$u || (int)$u['is_owner']===1){flash('error','Invalid sub-user.');redirect('users.php');}
        try{
            $name=trim((string)($_POST['display_name']??'')); if($name==='')$name=$u['username'];
            $role=(string)($_POST['role']??'member'); $all=!empty($_POST['all_vaults']);
            $perms=[]; foreach(['create_vault','manage_platforms','manage_backups','view_activity','reveal_codes','copy_codes','add_codes','mark_codes','delete_codes','edit_vaults','delete_vaults'] as $k)$perms[$k]=isset($_POST['perm'][$k]);
            $pdo->beginTransaction();
            $pdo->prepare('UPDATE users SET display_name=?,role=?,all_vaults=?,updated_at=? WHERE id=?')->execute([substr($name,0,100),$role,$all?1:0,time(),$uid]);
            $pdo->prepare('INSERT INTO user_permissions(user_id,create_vault,manage_platforms,manage_users,manage_settings,manage_backups,view_activity,reveal_codes,copy_codes,add_codes,mark_codes,delete_codes,manage_codes,edit_vaults,delete_vaults) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE create_vault=VALUES(create_vault),manage_platforms=VALUES(manage_platforms),manage_users=0,manage_settings=0,manage_backups=VALUES(manage_backups),view_activity=VALUES(view_activity),reveal_codes=VALUES(reveal_codes),copy_codes=VALUES(copy_codes),add_codes=VALUES(add_codes),mark_codes=VALUES(mark_codes),delete_codes=VALUES(delete_codes),manage_codes=VALUES(manage_codes),edit_vaults=VALUES(edit_vaults),delete_vaults=VALUES(delete_vaults)')->execute([$uid,(int)$perms['create_vault'],(int)$perms['manage_platforms'],0,0,(int)$perms['manage_backups'],(int)$perms['view_activity'],(int)$perms['reveal_codes'],(int)$perms['copy_codes'],(int)$perms['add_codes'],(int)$perms['mark_codes'],(int)$perms['delete_codes'],((int)$perms['add_codes']||(int)$perms['mark_codes']||(int)$perms['delete_codes']),(int)$perms['edit_vaults'],(int)$perms['delete_vaults']]);
            $pdo->prepare('DELETE FROM vault_access WHERE user_id=?')->execute([$uid]);
            if(!$all){$ins=$pdo->prepare('INSERT INTO vault_access(user_id,vault_id,can_view,can_reveal,can_copy,can_add,can_mark,can_delete_code,can_manage_codes,can_edit,can_delete) VALUES(?,?,?,?,?,?,?,?,?,?,?)');foreach(array_unique(array_map('intval',$_POST['vaults']??[])) as $vid){if(!get_vault($vid))continue;$ins->execute([$uid,$vid,1,(int)$perms['reveal_codes'],(int)$perms['copy_codes'],(int)$perms['add_codes'],(int)$perms['mark_codes'],(int)$perms['delete_codes'],((int)$perms['add_codes']||(int)$perms['mark_codes']||(int)$perms['delete_codes']),(int)$perms['edit_vaults'],(int)$perms['delete_vaults']]);}}
            $newPass=(string)($_POST['password']??'');
            if($newPass!==''){
                if(strlen($newPass)<12)throw new RuntimeException('New password must be at least 12 characters.');
                $hash=password_hash($newPass,defined('PASSWORD_ARGON2ID')?PASSWORD_ARGON2ID:PASSWORD_DEFAULT); if($hash===false)throw new RuntimeException('Could not create password hash.');
                [$salt,$cipher,$nonce]=wrap_data_key(key_from_session(),$newPass);
                $pdo->prepare('UPDATE users SET password_hash=?,password_salt=?,key_ciphertext=?,key_nonce=?,updated_at=? WHERE id=?')->execute([$hash,$salt,$cipher,$nonce,time(),$uid]);
            }
            $pdo->commit(); provision_user_access_keys($uid,$all,$all?[]:array_values(array_unique(array_map('intval',$_POST['vaults']??[]))),key_from_session()); log_activity('Updated sub-user'); flash('success','Sub-user permissions saved.');
        }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('error',$e->getMessage());}
        redirect('users.php?edit='.$uid);
    }
    if($action==='toggle_user'){$uid=(int)($_POST['user_id']??0);$u=get_user($uid);if($u&&!$u['is_owner']){$pdo->prepare('UPDATE users SET enabled=1-enabled,updated_at=? WHERE id=?')->execute([time(),$uid]);log_activity('Changed sub-user status');flash('success',((int)$u['enabled'])?'Sub-user disabled.':'Sub-user enabled.');}redirect('users.php');}
    if($action==='delete_user'){$uid=(int)($_POST['user_id']??0);$u=get_user($uid);if($u&&!$u['is_owner']){$pdo->prepare('DELETE FROM users WHERE id=?')->execute([$uid]);log_activity('Deleted sub-user');flash('success','Sub-user deleted.');}redirect('users.php');}
}
$users=$pdo->query('SELECT * FROM users WHERE is_owner=0 ORDER BY enabled DESC,display_name,username')->fetchAll();
$vaults=$pdo->query('SELECT id,name,account,category FROM vaults ORDER BY favorite DESC,name')->fetchAll();
$editId=(int)($_GET['edit']??0); $editing=$editId?get_user($editId):null; $editingPerm=$editing?get_user_permissions($editId):[]; $editingAccess=$editing?get_user_vault_access($editId):[];
$pageTitle='Users'; include __DIR__.'/app/header.php';
?>
<div class="topbar users-topbar"><div><div class="eyebrow">Team access</div><div class="title">Users</div><p class="subtitle">Give employees the exact access they need without sharing the master password.</p></div><div class="actions"><a class="btn" href="settings.php">Settings</a></div></div>
<section class="card users-hero"><div class="users-hero-copy"><div class="users-hero-icon">♙</div><div><h2>Sub-users & permissions</h2><p>Each employee gets their own login. Access can be limited globally and per vault.</p></div></div><div class="users-security-pill">Master password stays private</div></section>

<?php if($editing): ?>
<section class="card user-editor"><div class="section-head"><div><h2>Edit <?=e($editing['display_name'])?></h2><p>Change permissions, vault access, or reset this user's password.</p></div><a class="btn" href="users.php">Cancel</a></div>
<form method="post" class="user-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="update_user"><input type="hidden" name="user_id" value="<?=$editing['id']?>">
<div class="form-grid"><div class="field"><label>DISPLAY NAME</label><input name="display_name" value="<?=e($editing['display_name'])?>" maxlength="100" required></div><div class="field"><label>USERNAME</label><input value="<?=e($editing['username'])?>" disabled></div><div class="field"><label>ROLE <span>LABEL ONLY</span></label><select name="role"><option value="manager" <?=$editing['role']==='manager'?'selected':''?>>Manager</option><option value="member" <?=$editing['role']==='member'?'selected':''?>>Member</option><option value="viewer" <?=$editing['role']==='viewer'?'selected':''?>>Viewer</option></select><small class="field-help">Just an organizational label. Actual access comes from the permissions below.</small></div><div class="field"><label>NEW PASSWORD <span>OPTIONAL</span></label><input type="password" name="password" minlength="12" autocomplete="new-password" placeholder="Leave blank to keep current"></div></div>
<div class="permission-layout"><div><h3>Global permissions</h3><p>These control actions outside individual vaults.</p><div class="permission-grid"><?php foreach([['create_vault','Create vaults'],['manage_platforms','Manage platforms'],['manage_backups','Manage backups'],['view_activity','View activity log']] as [$k,$label]): ?><label class="check-card"><input type="checkbox" name="perm[<?=$k?>]" <?=$editingPerm[$k]?'checked':''?>><span><b><?=e($label)?></b><small><?=e(['create_vault'=>'Create new vaults','manage_platforms'=>'Add/remove platform entries','manage_settings'=>'Change security preferences','manage_backups'=>'Create and restore backups','view_activity'=>'See security activity','add_codes'=>'Add new recovery codes','mark_codes'=>'Mark a code used or unused','delete_codes'=>'Permanently delete recovery codes'][ $k])?></small></span></label><?php endforeach; ?></div></div>
<div><h3>Vault & code permissions</h3><p>Each permission is independent. Select only what this user should be able to do.</p><div class="permission-grid"><?php foreach([['reveal_codes','Reveal codes'],['copy_codes','Copy codes'],['add_codes','Add recovery codes'],['mark_codes','Mark codes used / unused'],['delete_codes','Delete recovery codes'],['edit_vaults','Edit vault details'],['delete_vaults','Delete vaults']] as [$k,$label]): ?><label class="check-card"><input type="checkbox" name="perm[<?=$k?>]" <?=$editingPerm[$k]?'checked':''?>><span><b><?=e($label)?></b><small>Applies to every assigned vault.</small></span></label><?php endforeach; ?></div></div></div>
<label class="all-vaults-card"><input type="checkbox" name="all_vaults" value="1" <?=$editing['all_vaults']?'checked':''?> data-all-vaults><span><b>Give access to all vaults</b><small>Includes every current and future vault, but only with the permissions checked above.</small></span></label>
<div class="vault-access-picker" data-vault-access-picker><div class="section-head"><div><h3>Vault access</h3><p>Choose which vaults this user can open.</p></div><span class="vault-access-note">Scope only — permissions still apply</span></div><div class="vault-access-list"><?php foreach($vaults as $v): ?><label class="vault-access-item"><input type="checkbox" name="vaults[]" value="<?=$v['id']?>" <?=isset($editingAccess[$v['id']])?'checked':''?>><span><b><?=e($v['name'])?></b><small><?=e($v['account']?:$v['category'])?></small></span></label><?php endforeach; ?><?php if(!$vaults): ?><div class="empty">No vaults yet.</div><?php endif; ?></div></div>
<div class="user-form-footer"><span>Changes take effect on the user's next request.</span><button class="btn primary" type="submit">Save permissions</button></div>
</form></section>
<?php else: ?>
<section class="card user-editor"><div class="section-head"><div><h2>Create a sub-user</h2><p>Never share the master password with an employee.</p></div></div>
<form method="post" class="user-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="add_user"><div class="form-grid"><div class="field"><label>USERNAME</label><input name="username" maxlength="60" required placeholder="e.g. rahim"></div><div class="field"><label>DISPLAY NAME</label><input name="display_name" maxlength="100" required placeholder="Rahim Ahmed"></div><div class="field"><label>PASSWORD</label><input type="password" name="password" minlength="12" autocomplete="new-password" required placeholder="At least 12 characters"></div><div class="field"><label>ROLE <span>LABEL ONLY</span></label><select name="role"><option value="viewer">Viewer</option><option value="member" selected>Member</option><option value="manager">Manager</option></select><small class="field-help">Just an organizational label. Actual access comes from the permissions below.</small></div></div>
<div class="permission-layout"><div><h3>Global permissions</h3><div class="permission-grid"><?php foreach([['create_vault','Create vaults'],['manage_platforms','Manage platforms'],['manage_backups','Manage backups'],['view_activity','View activity log']] as [$k,$label]): ?><label class="check-card"><input type="checkbox" name="perm[<?=$k?>]"><span><b><?=e($label)?></b><small><?=e(['create_vault'=>'Create new vaults','manage_platforms'=>'Add/remove platform entries','manage_settings'=>'Change security preferences','manage_backups'=>'Create and restore backups','view_activity'=>'See security activity','add_codes'=>'Add new recovery codes','mark_codes'=>'Mark a code used or unused','delete_codes'=>'Permanently delete recovery codes'][$k])?></small></span></label><?php endforeach; ?></div></div><div><h3>Vault & code permissions</h3><div class="permission-grid"><?php foreach([['reveal_codes','Reveal codes'],['copy_codes','Copy codes'],['add_codes','Add recovery codes'],['mark_codes','Mark codes used / unused'],['delete_codes','Delete recovery codes'],['edit_vaults','Edit vault details'],['delete_vaults','Delete vaults']] as [$k,$label]): ?><label class="check-card"><input type="checkbox" name="perm[<?=$k?>]"><span><b><?=e($label)?></b><small>Applies to assigned vaults.</small></span></label><?php endforeach; ?></div></div></div>
<label class="all-vaults-card"><input type="checkbox" name="all_vaults" value="1" data-all-vaults><span><b>Give access to all vaults</b><small>Includes every current and future vault, but only with the permissions checked above.</small></span></label>
<div class="vault-access-picker" data-vault-access-picker><div class="section-head"><div><h3>Vault access</h3><p>Select the vaults this user can open.</p></div></div><div class="vault-access-list"><?php foreach($vaults as $v): ?><label class="vault-access-item"><input type="checkbox" name="vaults[]" value="<?=$v['id']?>"><span><b><?=e($v['name'])?></b><small><?=e($v['account']?:$v['category'])?></small></span></label><?php endforeach; ?><?php if(!$vaults): ?><div class="empty">No vaults yet.</div><?php endif; ?></div></div>
<div class="user-form-footer"><span>The user can sign in with their own username and password.</span><button class="btn primary" type="submit">Create sub-user</button></div></form></section>
<?php endif; ?>

<section class="card user-list-card"><div class="section-head"><div><h2>Your team</h2><p>Manage active and disabled sub-users.</p></div><span class="activity-count"><?=count($users)?> sub-user<?=count($users)===1?'':'s'?></span></div><div class="user-list"><?php if(!$users): ?><div class="empty"><strong>No sub-users yet.</strong><br>Create one above when you're ready to share limited access.</div><?php endif; ?><?php foreach($users as $u): ?><div class="user-row"><div class="user-avatar"><?=e(strtoupper(substr($u['display_name'],0,1)))?></div><div class="user-copy"><strong><?=e($u['display_name'])?></strong><span>@<?=e($u['username'])?> · <?=e(ucfirst($u['role']))?></span></div><span class="user-status <?=((int)$u['enabled'])?'enabled':'disabled'?>"><?=((int)$u['enabled'])?'Active':'Disabled'?></span><div class="user-actions"><a class="btn" href="users.php?edit=<?=$u['id']?>">Edit access</a><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="toggle_user"><input type="hidden" name="user_id" value="<?=$u['id']?>"><button class="btn" type="submit"><?=((int)$u['enabled'])?'Disable':'Enable'?></button></form><form method="post" onsubmit="return confirm('Delete this sub-user?')"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete_user"><input type="hidden" name="user_id" value="<?=$u['id']?>"><button class="btn danger" type="submit">Delete</button></form></div></div><?php endforeach; ?></div></section>
<?php include __DIR__.'/app/footer.php'; ?>
<script>
(()=>{const all=document.querySelector('[data-all-vaults]'),picker=document.querySelector('[data-vault-access-picker]');function sync(){if(!all||!picker)return;picker.classList.toggle('disabled',all.checked);picker.querySelectorAll('input[type=checkbox]').forEach(x=>x.disabled=all.checked)}sync();all?.addEventListener('change',sync)})();
</script>
