<?php
/** VaultOTP | Author: ItNexBD | https://itnexbd.com | https://github.com/NecharUddin */
require_once __DIR__.'/app/config.php'; init_db(); require_login();
$q=trim((string)($_GET['q']??'')); $cat=trim((string)($_GET['category']??''));
[$scopeSql,$scopeParams]=accessible_vault_sql('v'); $sql="SELECT v.*,p.icon platform_icon,COUNT(c.id) total,COALESCE(SUM(c.used=0),0) unused FROM vaults v LEFT JOIN platforms p ON p.name=v.name AND p.enabled=1 LEFT JOIN codes c ON c.vault_id=v.id WHERE 1{$scopeSql}"; $params=$scopeParams;
if($q!==''){$sql.=" AND (v.name LIKE ? OR v.account LIKE ? OR v.category LIKE ? OR v.notes LIKE ?)";$x="%$q%";$params=array_merge($params,[$x,$x,$x,$x]);}
if($cat!==''){$sql.=" AND v.category=?";$params[]=$cat;}$sql.=" GROUP BY v.id ORDER BY v.favorite DESC,v.updated_at DESC";
$stmt=db()->prepare($sql);$stmt->execute($params);$vaults=$stmt->fetchAll();$cats=categories();$pageTitle='Vaults';include __DIR__.'/app/header.php';
?>
<div class="topbar vaults-topbar"><div><div class="eyebrow">All saved services</div><div class="title">Vaults</div><p class="subtitle">Browse every vault, search by service or account, and open one to manage its recovery codes.</p></div><div class="actions"><button class="btn theme-btn" data-theme-toggle type="button"><span data-theme-label>◐ Dark mode</span></button><?php if(can('create_vault')): ?><a class="btn primary" href="vault.php?new=1">＋ New vault</a><?php endif; ?></div></div>
<section class="vaults-toolbar card"><form class="vaults-search-form" method="get"><span>⌕</span><input name="q" value="<?=e($q)?>" placeholder="Search vaults, accounts, categories…" aria-label="Search vaults"></form><?php if($cats): ?><div class="chips vaults-filter-chips"><?php foreach($cats as $c): ?><a class="<?=($cat===$c)?'active':''?>" href="?category=<?=urlencode($c)?>"><?=e($c)?></a><?php endforeach; ?><?php if($cat||$q): ?><a href="vaults.php">Clear filters</a><?php endif; ?></div><?php endif; ?></section>
<section class="all-vaults-section"><div class="section-head vaults-list-head"><div><h2><?=count($vaults)?> <?=count($vaults)===1?'vault':'vaults'?></h2><p>All your saved services are shown here.</p></div></div><?php if($vaults): ?><div class="vault-grid dashboard-vault-grid"><?php foreach($vaults as $v): ?><a class="vault-card dashboard-vault-card" href="vault.php?id=<?=$v['id']?>"><div class="vault-card-top"><div class="vault-icon-large"><?=platform_image(['name'=>$v['name'],'icon'=>$v['platform_icon']],'vault-platform-icon')?></div><span class="vault-arrow">↗</span></div><div class="vault-name-row"><strong><?=e($v['name'])?></strong><?php if((int)$v['favorite']): ?><span class="favorite-mark">★</span><?php endif; ?></div><div class="vault-account"><?=e($v['account']?:'No account label')?></div><div class="vault-card-footer"><span><?=e($v['category'])?></span><span><b><?=$v['unused']?></b> unused <i>·</i> <?=$v['total']?> total</span></div></a><?php endforeach; ?></div><?php else: ?><div class="empty-vault-state card"><div class="empty-vault-icon">⌕</div><h3><?=($q||$cat)?'No matching vaults':'No vaults yet'?></h3><p><?=($q||$cat)?'Try another search or clear the current filter.':'Create your first vault to start storing recovery codes.'?></p><?php if($q||$cat): ?><a class="btn" href="vaults.php">Clear filters</a><?php else: ?><a class="btn primary" href="vault.php?new=1">Create your first vault</a><?php endif; ?></div><?php endif; ?></section>
<?php include __DIR__.'/app/footer.php'; ?>
